backend:
  name: git-gateway
  branch: main

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "sitio"
    label: "Sitio Web"
    files:
      - file: "index.html"
        label: "Página principal"
        name: "index"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Texto principal", name: "texto", widget: "text" }
          - { label: "Imagen principal", name: "imagen", widget: "image" }
          - { label: "Precio", name: "precio", widget: "string" }




