backend:
  name: git-gateway
  branch: main
  repo: diswebsolucionesdigitales/disweb

# (Podés quitar o dejar "local_backend" comentado, no se usa en Netlify)
# local_backend: true

media_folder: "assets/img"     # Carpeta donde se guardan las imágenes
public_folder: "/assets/img"   # Ruta pública para mostrar esas imágenes

# Configuración de contenido editable
collections:
  - name: "settings"
    label: "Configuración del Sitio"
    files:
      - name: "site_settings"
        label: "Ajustes Generales"
        file: "_data/settings.json"
        fields:
          - { label: "Título del Header", name: "titulo_header", widget: "string" }
          - { label: "Título Principal (Hero)", name: "titulo_hero", widget: "string" }
          - { label: "Teléfono", name: "telefono", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Texto Nosotros", name: "nosotros", widget: "text" }
          - { label: "Precio Plan Básico", name: "precio_basico", widget: "string" }
          - { label: "Precio Plan Avanzado", name: "precio_avanzado", widget: "string" }
          - { label: "Imagen Hero", name: "hero_img", widget: "image" }
