backend:
  name: git-gateway
  branch: main  # o master, según tu repo
media_folder: "assets/img/uploads" # donde se guardan las imágenes
public_folder: "/assets/img/uploads"

collections:
  - name: "sitio"
    label: "Sitio Web"
    files:
      - file: "index.html"
        label: "Página principal"
        name: "index"
        fields:
          - { label: "Título Header", name: "titulo_header", widget: "string" }
          - { label: "Título Hero", name: "titulo_hero", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Teléfono", name: "telefono", widget: "string" }
          - { label: "Texto Nosotros", name: "nosotros", widget: "text" }
          - { label: "Precio Plan Básico", name: "precio_basico", widget: "string" }
          - { label: "Precio Plan Avanzado", name: "precio_avanzado", widget: "string" }
          - { label: "Imagen Principal", name: "hero_img", widget: "image" }




