backend:
  name: github
  repo: diswebsolucionesdigitales/disweb
  branch: main
  site_domain: diswebsolucionesdigitales.github.io
  base_url: https://diswebsolucionesdigitales.github.io

publish_mode: editorial_workflow
media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

collections:
  - name: "settings"
    label: "Configuración del Sitio"
    files:
      - name: "site_settings"
        label: "Ajustes Generales"
        file: "_data/settings.json"
        fields:
          - { label: "Título del Header", name: "titulo_header", widget: "string" }
          - { label: "Título Principal (Hero)", name: "titulo_hero", widget: "string" }
          - { label: "Teléfono", name: "telefono", widget: "string" }

          - { label: "Email", name: "email", widget: "string" }

          
