backend:
  name: git-gateway
  repo: diswebsolucionesdigitales/disweb
  branch: main

# Agregá esta línea para deshabilitar Netlify Identity:
local_backend: true

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "settings"
    label: "Configuración del Sitio"
    files:
      - name: "site_settings"
        label: "Ajustes Generales"
        file: "_data/settings.json"
        fields:
          - { label: "Título del Header", name: "titulo_header", widget: "string" }
          - { label: "Título Principal (Hero)", name: "titulo_hero", widget: "string" }
          - { label: "Teléfono", name: "telefono", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }


